import { chromium } from '../worker/node_modules/@playwright/test/index.mjs';
import mysql from '../worker/node_modules/mysql2/promise.js';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import assert from 'node:assert/strict';
const config = JSON.parse(await readFile(new URL('../etc/config.json', import.meta.url), 'utf8'));
const db = await mysql.createConnection(config.db);
const browser = await chromium.launch({args:['--no-sandbox']});
const id = randomUUID();
const [[savedCategories]] = await db.query("SELECT value FROM settings WHERE `key`='lucky_categories'");
const [[savedPrompt]] = await db.query("SELECT value FROM settings WHERE `key`='lucky_prompt'");
try {
  const [[owner]] = await db.query("SELECT id FROM users WHERE username='admin'");
  const idea = {name:'Suggestion UI verification', summary:'A temporary idea for queue verification.', category:'education', project_type:'cli', initial_prompt:'Build a small local learning tool.', recommended_worker:'codex', thinking:'high', enable_agents:false, dynamic_work:false, scaffold_files:[]};
  await db.execute("INSERT INTO lucky_drafts(id,user_id,revision,status,with_scaffold,result) VALUES(?,?,0,'ready',0,?)", [id,owner.id,JSON.stringify(idea)]);
  await db.execute("INSERT INTO suggestions(draft_id,batch_date,slot) VALUES(?,'2000-01-01',?)", [id,Math.floor(Math.random()*2000000000)]);
  const page = await browser.newPage();
  const errors=[]; page.on('pageerror', e=>errors.push(e.message));
  await page.goto(process.env.AIWORKER_TEST_URL || config.url);
  const password=(await readFile(new URL('../docs/ADMIN_CREDS.md',import.meta.url),'utf8')).match(/^Password: (.+)$/m)[1];
  await page.getByLabel('Username',{exact:true}).fill('admin');
  await page.getByLabel('Password',{exact:true}).fill(password);
  await page.getByRole('button',{name:'Sign in →'}).click();
  await page.locator('#jobs-body').waitFor();
  assert.equal(await page.locator('#lucky-scaffold').isChecked(),false);
  await page.locator('[data-view=suggestions]').click();
  await page.locator(`[data-pick="${id}"]`).click();
  await page.locator("#project-dialog[open]").waitFor();
  assert.equal(await page.locator('#project-form [name=scaffold_source]').inputValue(),'kawaiipantsu');
  assert.equal(await page.locator('#project-form [name=name]').inputValue(),idea.name);
  assert.equal(await page.locator('#project-form [name=model]').inputValue(),'gpt-6-astra');
  assert.equal(await page.locator('#project-form [name=effort]').inputValue(),'medium');
  await page.locator('#project-form [name=provider]').selectOption('claude');
  assert.equal(await page.locator('#project-form [name=model]').inputValue(),'fable');
  assert.equal(await page.locator('#project-form [name=effort]').inputValue(),'high');
  await page.getByRole('button',{name:'Abort',exact:true}).click();
  await page.waitForTimeout(300);
  const [[draft]]=await db.execute('SELECT status FROM lucky_drafts WHERE id=?',[id]);
  assert.equal(draft.status,'ready');
  await page.locator(`[data-drop="${id}"]`).click();
  await page.locator(`[data-drop="${id}"]`).waitFor({state:'detached'});
  const [[dropped]]=await db.execute('SELECT status FROM lucky_drafts WHERE id=?',[id]);
  assert.equal(dropped.status,'cancelled');
  await page.getByRole('link',{name:'Administration',exact:true}).click();
  await page.locator('#suggestions-form').waitFor();
  assert.equal(await page.locator('#suggestions-form [name=count]').inputValue(),'2');
  const prompt = page.locator('#lucky-prompt-form [name=prompt]');
  await page.waitForFunction(() => document.querySelector('#lucky-prompt-form textarea')?.value.length > 0);
  await prompt.fill('Generate small educational terminal games. {{category}}');
  await page.locator('#lucky-prompt-form button[type=submit], #lucky-prompt-form button.primary').click();
  await page.waitForFunction(() => document.querySelector('#toast')?.textContent === 'Generation prompt saved');
  const [[custom]] = await db.query("SELECT value FROM settings WHERE `key`='lucky_prompt'");
  assert.equal(JSON.parse(custom.value),'Generate small educational terminal games. {{category}}');
  await page.locator('#lucky-prompt-reset').click();
  await page.waitForFunction(() => document.querySelector('#lucky-prompt-form textarea')?.value.startsWith('You are a creative product designer'));
  const categoryInput = page.locator('#lucky-categories-form [name=categories]');
  await categoryInput.fill(' Botanical puzzles \nMusic learning\nBotanical puzzles');
  await page.locator('#lucky-categories-form button.primary').click();
  await page.waitForFunction(() => document.querySelector('#toast')?.textContent === 'Generation categories saved');
  const [[customCategories]] = await db.query("SELECT value FROM settings WHERE `key`='lucky_categories'");
  assert.deepEqual(JSON.parse(customCategories.value), ['Botanical puzzles', 'Music learning']);
  await page.reload();
  await page.waitForFunction(() => document.querySelector('#lucky-categories-form textarea')?.value === 'Botanical puzzles\nMusic learning');
  await categoryInput.fill('x'.repeat(101));
  await page.locator('#lucky-categories-form button.primary').click();
  await page.waitForFunction(() => document.querySelector('#toast')?.textContent.includes('Each category must contain'));
  await page.locator('#lucky-categories-reset').click();
  await page.waitForFunction(() => document.querySelector('#lucky-categories-form textarea')?.value.startsWith('security tools'));
  assert.deepEqual(errors,[]);
  console.log('Suggestion summary, Pick, Kawaiipantsu default, abort preservation, Drop, and administration passed.');
} finally {
  await browser.close();
  await db.execute('DELETE FROM lucky_drafts WHERE id=?',[id]);
  if (savedPrompt) await db.execute("INSERT INTO settings(`key`,value) VALUES('lucky_prompt',?) ON DUPLICATE KEY UPDATE value=VALUES(value)",[savedPrompt.value]);
  else await db.query("DELETE FROM settings WHERE `key`='lucky_prompt'");
  if (savedCategories) await db.execute("INSERT INTO settings(`key`,value) VALUES('lucky_categories',?) ON DUPLICATE KEY UPDATE value=VALUES(value)",[savedCategories.value]);
  else await db.query("DELETE FROM settings WHERE `key`='lucky_categories'");
  await db.end();
}
