CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(80) UNIQUE NOT NULL,
 password_hash VARCHAR(255) NOT NULL, role ENUM('admin','operator') NOT NULL DEFAULT 'operator',
 active BOOLEAN NOT NULL DEFAULT 1, session_version INT NOT NULL DEFAULT 1, created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS settings (`key` VARCHAR(80) PRIMARY KEY, value LONGTEXT NOT NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS jobs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL,
 workspace VARCHAR(700) COLLATE utf8mb4_bin UNIQUE NOT NULL, workspace_ready BOOLEAN NOT NULL DEFAULT 0, INDEX slug(slug),
 prompt MEDIUMTEXT NOT NULL, provider ENUM('codex','claude') NOT NULL, model VARCHAR(100) NOT NULL,
 mode VARCHAR(40) NOT NULL, effort VARCHAR(20) NOT NULL, agents BOOLEAN DEFAULT 0, dynamic_work BOOLEAN DEFAULT 0,
 status VARCHAR(30) NOT NULL DEFAULT 'queued', summary TEXT, session_id VARCHAR(100),
 attempts INT NOT NULL DEFAULT 0, rate_attempts INT NOT NULL DEFAULT 0, retry_at DATETIME(3), queued_at DATETIME(3), started_at DATETIME(3), finished_at DATETIME(3),
 control VARCHAR(20), created_by BIGINT UNSIGNED NOT NULL, created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 INDEX dispatch(status,retry_at), INDEX provider_status(provider,status), FOREIGN KEY(created_by) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS uploads (job_id BIGINT UNSIGNED PRIMARY KEY, filename VARCHAR(255), data LONGBLOB NOT NULL, FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, job_id BIGINT UNSIGNED NOT NULL, kind VARCHAR(30) NOT NULL, body MEDIUMTEXT NOT NULL, created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3), INDEX(job_id,id), FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS messages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, job_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, body TEXT NOT NULL, delivered_at DATETIME(3), created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3), INDEX(job_id,delivered_at), FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS questions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, job_id BIGINT UNSIGNED NOT NULL, question TEXT NOT NULL, answer TEXT, answered_by BIGINT UNSIGNED, created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3), answered_at DATETIME(3), INDEX(job_id), FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED, action VARCHAR(80) NOT NULL, target VARCHAR(160), ip VARCHAR(45), detail TEXT, created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS provider_state (provider VARCHAR(20) PRIMARY KEY, cooldown_until DATETIME(3), reason TEXT) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS webhooks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL, url TEXT NOT NULL, enabled BOOLEAN DEFAULT 1, created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS webhook_deliveries (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, webhook_id BIGINT UNSIGNED NOT NULL, job_id BIGINT UNSIGNED NOT NULL, status VARCHAR(30) NOT NULL, attempts INT DEFAULT 0, next_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3), delivered_at DATETIME(3), last_error TEXT, INDEX(next_at,delivered_at), FOREIGN KEY(webhook_id) REFERENCES webhooks(id) ON DELETE CASCADE, FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS openai_connection (
 id TINYINT PRIMARY KEY, revision INT NOT NULL DEFAULT 0,
 mode ENUM('none','api_key','chatgpt') NOT NULL DEFAULT 'none',
 credential MEDIUMTEXT, label VARCHAR(160), verified_at DATETIME(3), last_error VARCHAR(500),
 updated_by BIGINT UNSIGNED, updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS openai_logins (
 id CHAR(36) PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, revision INT NOT NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'queued', verification_url VARCHAR(255), user_code VARCHAR(40),
 error VARCHAR(500), created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3), expires_at DATETIME(3),
 INDEX(status,created_at), FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS lucky_drafts (
 id CHAR(36) PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, revision INT NOT NULL,
 kind ENUM('idea','test') NOT NULL DEFAULT 'idea', status VARCHAR(24) NOT NULL DEFAULT 'queued',
 with_scaffold BOOLEAN NOT NULL DEFAULT 0, result MEDIUMTEXT, scaffold MEDIUMBLOB,
 error VARCHAR(500), created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3), finished_at DATETIME(3),
 INDEX(status,created_at), INDEX(user_id,created_at), FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
